class Symbol
  def titleize
    self.to_s.titleize
  end
end

if !ENV["MERCHANTS_WITH_CUSTOM_STORE_SLUGS_CSV"].nil?
  MERCHANTS_WITH_CUSTOM_STORE_SLUGS = ENV["MERCHANTS_WITH_CUSTOM_STORE_SLUGS_CSV"].split(',')
else
  MERCHANTS_WITH_CUSTOM_STORE_SLUGS = ['mason-s-store']
end

if !ENV["PRODUCT_PAGINATION_SIZE"].nil?
  PRODUCT_PAGINATION_SIZE = ENV["PRODUCT_PAGINATION_SIZE"].to_i
else
  PRODUCT_PAGINATION_SIZE = 5
end
