# ~/.tmuxinator/gramgoods.yml

project_name: gramgoods
project_root: ~/projects/gramgoods
pre: unset $DATABASE_URL
tabs:
  - editor:
      layout: main-vertical
      panes:
        - vim
        - #empty
  - server: foreman start
  - console: pry
